# SQL for Beginners (MySQL): a hands-on Colab lab
**A real MySQL 8 server runs inside this Colab session. No account, no download, no local install.** Run cells in order from the top (*Runtime > Run all*, or Shift+Enter on each cell).

This is the same dialect you use in **MySQL Workbench** for the MSDS 525 Final Project, so everything here transfers directly.

**Topics:** DDL (CREATE, ALTER, DROP) · DML (INSERT, UPDATE, DELETE) · SELECT, WHERE, ORDER BY, LIMIT · functions (aggregate, text, number, date, NULL, CASE) · GROUP BY and HAVING · JOINs · subqueries, CTEs, views · window functions · set operations · transactions · staging and cleaning text data · practice exercises.

The sample data is **small and made up** (airport-traffic themed so it connects to the BNA project). It is *not* real data.

## 0. Setup: start MySQL
The next cell installs MySQL Server (about 1-2 minutes the first time), starts it, sets a throwaway password, creates a practice database called `sql_lab`, and defines two helpers:

- `%%sql` at the top of a cell runs plain SQL, just like a Workbench query tab. Separate statements with `;`.
- `sql("...")` runs one statement from Python and returns a table.

> The password below only protects a temporary server that disappears when the Colab session ends. Never reuse a real password in a notebook.

In [1]:
import subprocess, shutil, time, re, sys

PW = "colab_pass"                      # throwaway password for this session only

def sh(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)

# 1) install MySQL server if it is not installed yet
if not shutil.which("mysqld"):
    print("Installing MySQL Server (1-2 minutes)...")
    sh("DEBIAN_FRONTEND=noninteractive apt-get update -qq")
    r = sh("DEBIAN_FRONTEND=noninteractive apt-get install -y -qq mysql-server")
    if r.returncode != 0:
        print(r.stderr[-1500:]); raise SystemExit("MySQL install failed - see message above")

# 2) Python driver
try:
    import pymysql
except ImportError:
    sh(f"{sys.executable} -m pip install -q pymysql")
    import pymysql

# 3) start the server and wait until it answers
sh("service mysql start")
for _ in range(40):
    if sh("mysqladmin ping --silent").returncode == 0 or sh(f"mysqladmin -uroot -p{PW} ping --silent").returncode == 0:
        break
    time.sleep(1)

def _connect(db=None):
    return pymysql.connect(host="127.0.0.1", user="root", password=PW, database=db, autocommit=True)

# 4) set the root password (first run only), then connect
try:
    conn = _connect()
except pymysql.MySQLError:
    r = sh(f"mysql -uroot -e \"ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{PW}'; FLUSH PRIVILEGES;\"")
    if r.returncode != 0:
        sh(f"mysql -uroot -e \"ALTER USER 'root'@'localhost' IDENTIFIED BY '{PW}'; FLUSH PRIVILEGES;\"")
    conn = _connect()

# 5) a fresh practice database every time this cell runs
with conn.cursor() as cur:
    cur.execute("DROP DATABASE IF EXISTS sql_lab")
    cur.execute("CREATE DATABASE sql_lab")
conn.close()
conn = _connect("sql_lab")

import pandas as pd
from decimal import Decimal
from IPython.display import display

def _tidy(rows, cols):
    df = pd.DataFrame(rows, columns=cols)
    for j, c in enumerate(cols):
        vals = [r[j] for r in rows if r[j] is not None]
        if not vals:
            continue
        if all(isinstance(v, int) and not isinstance(v, bool) for v in vals):
            df[c] = pd.array([r[j] for r in rows], dtype="Int64")          # whole numbers stay whole (even with NULLs)
        elif all(isinstance(v, Decimal) for v in vals):                    # MySQL returns SUM()/AVG() as DECIMAL
            if all(v == v.to_integral_value() for v in vals):
                df[c] = pd.array([None if r[j] is None else int(r[j]) for r in rows], dtype="Int64")
            else:
                df[c] = df[c].astype(float)
    return df

def _split(text):
    text = re.sub(r"--[^\n]*", "", text)         # drop -- comments
    return [s.strip() for s in text.split(";") if s.strip()]

def run_sql(query, params=None):
    """Run ONE statement from Python. SELECT-type statements return a table; others print rows affected."""
    with conn.cursor() as cur:
        cur.execute(query, params)
        if cur.description:
            return _tidy(cur.fetchall(), [d[0] for d in cur.description])
        print(f"OK ({cur.rowcount} rows affected)")

def _sql_magic(line, cell=None):
    stmts = _split(cell if cell is not None else line)
    for s in stmts:
        with conn.cursor() as cur:
            cur.execute(s)
            if cur.description:
                display(_tidy(cur.fetchall(), [d[0] for d in cur.description]))
            else:
                print(f"OK ({cur.rowcount} rows affected)")

get_ipython().register_magic_function(_sql_magic, magic_kind="cell", magic_name="sql")
sql = run_sql                                       # sql("...") from Python

print("MySQL ready:", sql("SELECT VERSION() AS version").iloc[0, 0], "| database:", sql("SELECT DATABASE() AS db").iloc[0, 0])

MySQL ready: 8.0.46-0ubuntu0.24.04.4 | database: sql_lab

## 1. DDL: Data Definition Language
DDL defines the **structure** of the database: `CREATE`, `ALTER`, `DROP`.

A table has **columns** with **data types** and **constraints**:
| Constraint | Meaning |
|---|---|
| `PRIMARY KEY` | unique id for each row |
| `AUTO_INCREMENT` | MySQL numbers new rows for you |
| `NOT NULL` | value required |
| `UNIQUE` | no duplicates allowed |
| `DEFAULT x` | value used when none is given |
| `CHECK (...)` | rule the value must satisfy (enforced in MySQL 8.0.16+) |
| `FOREIGN KEY` | must match a row in another table |

Common types: `INT`, `DECIMAL(p,s)` (exact decimals), `VARCHAR(n)` (text up to n characters), `CHAR(n)`, `DATE`, `DATETIME`.

In [2]:
%%sql
CREATE TABLE road (
    road_id     INT AUTO_INCREMENT PRIMARY KEY,
    road_name   VARCHAR(60) NOT NULL UNIQUE,
    speed_limit INT,
    CONSTRAINT chk_speed CHECK (speed_limit BETWEEN 15 AND 75)
);

CREATE TABLE incidents (
    incident_id   INT AUTO_INCREMENT PRIMARY KEY,
    occurred_at   DATETIME NOT NULL,
    road_id       INT,
    incident_type VARCHAR(40) DEFAULT 'Unknown',
    injuries      INT DEFAULT 0,
    CONSTRAINT fk_incident_road FOREIGN KEY (road_id) REFERENCES road(road_id)
);

CREATE TABLE weather (
    day   DATE PRIMARY KEY,
    prcp  DECIMAL(5,2),          -- precipitation, inches
    tmax  INT                    -- max temperature, F
);

CREATE TABLE airport_ops (
    ops_month  CHAR(7) PRIMARY KEY,   -- 'YYYY-MM'
    arrivals   INT,
    departures INT
)

OK (0 rows affected)
OK (0 rows affected)
OK (0 rows affected)
OK (0 rows affected)

`SHOW TABLES` lists tables, `DESCRIBE` shows a table's columns, and `SHOW CREATE TABLE` shows the full definition.

In [3]:
%%sql
SHOW TABLES;
DESCRIBE incidents

  Tables_in_sql_lab
0       airport_ops
1         incidents
2              road
3           weather

           Field         Type Null  Key  Default           Extra
0    incident_id          int   NO  PRI      NaN  auto_increment
1    occurred_at     datetime   NO           NaN
2        road_id          int  YES  MUL      NaN
3  incident_type  varchar(40)  YES       Unknown
4       injuries          int  YES             0

**ALTER** changes an existing table. **CREATE INDEX** speeds up searches on a column. **DROP** deletes a table (and its data) for good.

In [4]:
%%sql
ALTER TABLE incidents ADD COLUMN severity VARCHAR(10);
CREATE INDEX idx_incidents_time ON incidents (occurred_at);
SHOW INDEX FROM incidents

OK (0 rows affected)
OK (0 rows affected)

,Table,Non_unique,Key_name,Seq_in_index,Column_name,Collation,Cardinality,Sub_part,Packed,Null,Index_type,Comment,Index_comment,Visible,Expression
0,incidents,0,PRIMARY,1,incident_id,A,0,None,None,,BTREE,,,YES,None
1,incidents,1,fk_incident_road,1,road_id,A,0,None,None,YES,BTREE,,,YES,None
2,incidents,1,idx_incidents_time,1,occurred_at,A,0,None,None,,BTREE,,,YES,None

In [5]:
%%sql
CREATE TABLE scratch (x INT);
DROP TABLE scratch;
SHOW TABLES

OK (0 rows affected)
OK (0 rows affected)

  Tables_in_sql_lab
0       airport_ops
1         incidents
2              road
3           weather

### Constraints in action
The database refuses data that breaks a rule. The three statements below **are supposed to fail**: each one breaks a rule we defined above. The cell catches MySQL's error message and prints it, so seeing three "Blocked" lines means everything is working. Nothing is inserted.

In [6]:
tests = {
  "CHECK: speed limit out of range":        "INSERT INTO road (road_name, speed_limit) VALUES ('Test Rd', 200)",
  "NOT NULL: missing road_name":            "INSERT INTO road (speed_limit) VALUES (30)",
  "FOREIGN KEY: road_id 999 does not exist": "INSERT INTO incidents (occurred_at, road_id) VALUES ('2026-01-01 08:00:00', 999)",
}
for label, stmt in tests.items():
    try:
        sql(stmt); print("PROBLEM - this should have been blocked:", label)
    except pymysql.MySQLError as e:
        print(f"OK, blocked as expected: {label}\n    MySQL error {e.args[0]}: {e.args[1]}\n")

OK, blocked as expected: CHECK: speed limit out of range
    MySQL error 3819: Check constraint 'chk_speed' is violated.

OK, blocked as expected: NOT NULL: missing road_name
    MySQL error 1364: Field 'road_name' doesn't have a default value

OK, blocked as expected: FOREIGN KEY: road_id 999 does not exist
    MySQL error 1452: Cannot add or update a child row: a foreign key constraint fails (`sql_lab`.`incidents`, CONSTRAINT `fk_incident_road` FOREIGN KEY (`road_id`) REFERENCES `road` (`road_id`))

## 2. DML: Data Manipulation Language
DML changes the **data**: `INSERT`, `UPDATE`, `DELETE`.

### INSERT

In [7]:
%%sql
INSERT INTO road (road_name, speed_limit) VALUES ('Donelson Pike', 45);
INSERT INTO road (road_name, speed_limit) VALUES
  ('Briley Parkway', 55),
  ('Murfreesboro Pike', 40),
  ('I-40', 70);
SELECT * FROM road

OK (1 rows affected)
OK (3 rows affected)

   road_id          road_name  speed_limit
0        1      Donelson Pike           45
1        2     Briley Parkway           55
2        3  Murfreesboro Pike           40
3        4               I-40           70

Now load many rows quickly from Python. The data is **generated with a fixed seed**, so everyone gets nearly identical results. (Real projects load CSV files instead; see the note after this cell.)

In [8]:
import random, datetime as dt
random.seed(525)

start = dt.date(2026, 1, 1)
days = [start + dt.timedelta(days=i) for i in range(90)]          # Jan-Mar 2026

# weather: one row per day
w_rows = []
for d in days:
    rain = random.random() < 0.35
    w_rows.append((d.isoformat(), round(random.uniform(0.05, 1.2), 2) if rain else 0.0, random.randint(35, 70)))

# incidents: more on rainy days; more at 7-9 AM and 4-6 PM
types = ["Crash", "Stalled vehicle", "Debris", "Minor collision"]
wx = {r[0]: r[1] for r in w_rows}
i_rows = []
for d in days:
    n = random.randint(0, 2) + (3 if wx[d.isoformat()] > 0 else 0)
    for _ in range(n):
        hour = random.choice([7, 8, 9, 16, 17, 17, 18, random.randint(0, 23)])
        ts = f"{d.isoformat()} {hour:02d}:{random.randint(0,59):02d}:00"
        i_rows.append((ts, random.randint(1, 4), random.choice(types), random.choice([0, 0, 0, 1, 2])))

with conn.cursor() as cur:
    cur.executemany("INSERT INTO weather (day, prcp, tmax) VALUES (%s, %s, %s)", w_rows)
    cur.executemany("INSERT INTO incidents (occurred_at, road_id, incident_type, injuries) VALUES (%s, %s, %s, %s)", i_rows)
    cur.executemany("INSERT INTO airport_ops VALUES (%s, %s, %s)",
                    [("2026-01", 11800, 11750), ("2026-02", 11200, 11300), ("2026-03", 13100, 13050)])
print(len(w_rows), "weather rows,", len(i_rows), "incident rows")

90 weather rows, 167 incident rows

> **Loading a real CSV** (for your project):
> - In **MySQL Workbench**: right-click the table > *Table Data Import Wizard*.
> - In Python: upload the file with the folder icon on the left, then
> ```python
> from sqlalchemy import create_engine
> engine = create_engine(f"mysql+pymysql://root:{PW}@127.0.0.1/sql_lab")
> pd.read_csv("Traffic_BNA_Feb2026.csv").to_sql("raw_traffic", engine, if_exists="replace", index=False)
> ```

### UPDATE and DELETE
**Always use WHERE** with `UPDATE` and `DELETE`. Without it, *every* row changes. Check with a `SELECT` first. Statements run in order, so a later `UPDATE` can overwrite an earlier one (below, rows that are both 'Low' type and have injuries end up 'High').

In [9]:
%%sql
SELECT COUNT(*) AS minor_collisions FROM incidents WHERE incident_type = 'Minor collision';
UPDATE incidents SET severity = 'Low'  WHERE incident_type IN ('Debris', 'Stalled vehicle');
UPDATE incidents SET severity = 'High' WHERE injuries >= 1;
UPDATE incidents SET severity = 'Medium' WHERE severity IS NULL;
SELECT severity, COUNT(*) AS n FROM incidents GROUP BY severity

   minor_collisions
0                41

OK (84 rows affected)
OK (73 rows affected)
OK (49 rows affected)

  severity   n
0   Medium  49
1     High  73
2      Low  45

In [10]:
%%sql
INSERT INTO incidents (incident_id, occurred_at, road_id) VALUES (9999, '2026-01-01 00:00:00', 1);
DELETE FROM incidents WHERE incident_id = 9999;
SELECT COUNT(*) AS rows_left FROM incidents

OK (1 rows affected)
OK (1 rows affected)

   rows_left
0        167

> **Workbench tip:** MySQL Workbench starts in *safe-updates mode*, which refuses an `UPDATE` or `DELETE` whose `WHERE` does not use a key column (error 1175). This Colab server has no such limit. In Workbench, either filter by the primary key, or turn it off under *Edit > Preferences > SQL Editor > Safe Updates* and reconnect.

## 3. SELECT: reading data
Order of writing: `SELECT` → `FROM` → `WHERE` → `GROUP BY` → `HAVING` → `ORDER BY` → `LIMIT`.

In [11]:
%%sql
SELECT * FROM incidents LIMIT 5

,incident_id,occurred_at,road_id,incident_type,injuries,severity
0,2,2026-01-01 17:35:00,3,Minor collision,0,Medium
1,3,2026-01-03 16:46:00,3,Debris,2,High
2,4,2026-01-04 18:02:00,4,Minor collision,0,Medium
3,5,2026-01-04 07:00:00,2,Stalled vehicle,1,High
4,6,2026-01-04 17:10:00,1,Minor collision,2,High

In [12]:
%%sql
SELECT incident_id AS id, incident_type AS type, injuries      -- AS gives a column a nicer name
FROM incidents
WHERE injuries > 0 AND incident_type = 'Crash'
ORDER BY occurred_at DESC                                       -- newest first
LIMIT 5

    id   type  injuries
0  159  Crash         2
1  152  Crash         1
2  148  Crash         1
3  145  Crash         1
4  141  Crash         2

**WHERE operators:** `=  <>  <  >  <=  >=`, `AND / OR / NOT`, `IN (...)`, `BETWEEN a AND b`, `LIKE` (`%` = any text, `_` = one character), `IS NULL`.

In [13]:
%%sql
SELECT day, prcp FROM weather WHERE prcp BETWEEN 0.5 AND 1.0 ORDER BY prcp DESC LIMIT 5;
SELECT DISTINCT incident_type FROM incidents;
SELECT * FROM road WHERE road_name LIKE '%Pike';
SELECT * FROM incidents WHERE severity IS NULL LIMIT 3

          day  prcp
0  2026-02-21  1.00
1  2026-02-07  0.93
2  2026-02-09  0.85
3  2026-01-26  0.68
4  2026-01-21  0.64

     incident_type
0  Minor collision
1           Debris
2  Stalled vehicle
3            Crash

   road_id          road_name  speed_limit
0        1      Donelson Pike           45
1        3  Murfreesboro Pike           40

Empty DataFrame
Columns: [incident_id, occurred_at, road_id, incident_type, injuries, severity]
Index: []

## 4. Functions
### 4a. Aggregate functions
They collapse many rows into one value: `COUNT, SUM, AVG, MIN, MAX`.

In [14]:
%%sql
SELECT COUNT(*)                 AS total_incidents,
       COUNT(DISTINCT road_id)  AS roads_involved,
       SUM(injuries)            AS total_injuries,
       ROUND(AVG(injuries), 2)  AS avg_injuries,
       MIN(occurred_at)         AS first_seen,
       MAX(occurred_at)         AS last_seen
FROM incidents

,total_incidents,roads_involved,total_injuries,avg_injuries,first_seen,last_seen
0,167,4,106,0.63,2026-01-01 17:35:00,2026-03-30 16:04:00

### 4b. Text functions
`UPPER, LOWER, LENGTH, SUBSTRING, LEFT, RIGHT, TRIM, REPLACE, CONCAT`. (Use `CONCAT`, not `||`; in MySQL `||` means OR.)

In [15]:
%%sql
SELECT road_name,
       UPPER(road_name)                     AS upper_name,
       LENGTH(road_name)                    AS name_length,
       SUBSTRING(road_name, 1, 5)           AS first5,
       REPLACE(road_name, 'Pike', 'Pk')     AS short_name,
       CONCAT(road_name, ' (', speed_limit, ' mph)') AS label
FROM road

,road_name,upper_name,name_length,first5,short_name,label
0,Donelson Pike,DONELSON PIKE,13,Donel,Donelson Pk,Donelson Pike (45 mph)
1,Briley Parkway,BRILEY PARKWAY,14,Brile,Briley Parkway,Briley Parkway (55 mph)
2,Murfreesboro Pike,MURFREESBORO PIKE,17,Murfr,Murfreesboro Pk,Murfreesboro Pike (40 mph)
3,I-40,I-40,4,I-40,I-40,I-40 (70 mph)

### 4c. Number functions
`ROUND, ABS, FLOOR, CEILING, MOD`, plus arithmetic `+ - * /`. In MySQL, `/` always gives a decimal; use `DIV` for whole-number division.

In [16]:
%%sql
SELECT ops_month, arrivals, departures,
       arrivals + departures                    AS total_ops,
       ROUND((arrivals + departures) / 31, 1)   AS avg_ops_per_day,
       (arrivals + departures) DIV 31           AS whole_number_division,
       ABS(arrivals - departures)               AS imbalance,
       ROUND(arrivals / departures, 4)          AS ratio
FROM airport_ops

,ops_month,arrivals,departures,total_ops,avg_ops_per_day,whole_number_division,imbalance,ratio
0,2026-01,11800,11750,23550,759.7,759,50,1.0043
1,2026-02,11200,11300,22500,725.8,725,100,0.9912
2,2026-03,13100,13050,26150,843.5,843,50,1.0038

### 4d. Date and time functions
| Need | MySQL function |
|---|---|
| date part of a datetime | `DATE(ts)` |
| hour | `HOUR(ts)` |
| weekday name / number | `DAYNAME(ts)` / `WEEKDAY(ts)` (0 = Monday) or `DAYOFWEEK(ts)` (1 = Sunday) |
| year / month | `YEAR(ts)`, `MONTH(ts)` |
| format as text | `DATE_FORMAT(ts, '%Y-%m')` |
| text → date | `STR_TO_DATE('03/14/2026 17:45', '%m/%d/%Y %H:%i')` |
| difference in days | `DATEDIFF(date1, date2)` |
| add time | `DATE_ADD(d, INTERVAL 7 DAY)` |

In [17]:
%%sql
SELECT occurred_at,
       DATE(occurred_at)                  AS day,
       HOUR(occurred_at)                  AS hour,
       DAYNAME(occurred_at)               AS weekday,
       DATE_FORMAT(occurred_at, '%Y-%m')  AS month_key
FROM incidents LIMIT 5;
SELECT STR_TO_DATE('03/14/2026 17:45', '%m/%d/%Y %H:%i') AS parsed,
       DATEDIFF('2026-03-31', '2026-01-01')              AS days_between,
       DATE_ADD('2026-01-01', INTERVAL 45 DAY)           AS plus_45_days

          occurred_at         day  hour   weekday month_key
0 2026-01-01 17:35:00  2026-01-01    17  Thursday   2026-01
1 2026-01-03 16:46:00  2026-01-03    16  Saturday   2026-01
2 2026-01-04 07:00:00  2026-01-04     7    Sunday   2026-01
3 2026-01-04 16:09:00  2026-01-04    16    Sunday   2026-01
4 2026-01-04 17:10:00  2026-01-04    17    Sunday   2026-01

               parsed  days_between plus_45_days
0 2026-03-14 17:45:00            89   2026-02-15

### 4e. NULL handling and CASE
`COALESCE(a, b)` returns the first non-NULL value; `IFNULL(a, b)` is the two-value version; `NULLIF(a, b)` returns NULL when a = b (handy to turn `''` into NULL). `CASE WHEN` is SQL's if/else.

In [18]:
%%sql
SELECT day, prcp, tmax,
       COALESCE(prcp, 0) AS prcp_clean,
       CASE WHEN prcp > 0 THEN 'Rain' ELSE 'No rain' END AS weather_state,
       CASE WHEN tmax < 40 THEN 'Cold'
            WHEN tmax < 60 THEN 'Cool'
            ELSE 'Mild' END                              AS temp_band
FROM weather LIMIT 6

          day  prcp  tmax  prcp_clean weather_state temp_band
0  2026-01-01  0.00    42        0.00       No rain      Cool
1  2026-01-02  0.00    45        0.00       No rain      Cool
2  2026-01-03  0.00    41        0.00       No rain      Cool
3  2026-01-04  0.37    63        0.37          Rain      Mild
4  2026-01-05  0.00    37        0.00       No rain      Cold
5  2026-01-06  0.00    50        0.00       No rain      Cool

## 5. GROUP BY and HAVING
`GROUP BY` makes one row per group; combine it with aggregates.
`WHERE` filters **rows before** grouping, `HAVING` filters **groups after** grouping.

In [19]:
%%sql
SELECT incident_type, COUNT(*) AS n, SUM(injuries) AS injuries
FROM incidents
GROUP BY incident_type
ORDER BY n DESC

     incident_type   n  injuries
0           Debris  42        28
1  Stalled vehicle  42        27
2            Crash  42        29
3  Minor collision  41        22

In [20]:
%%sql
-- Incidents by hour of day: where does congestion peak?
SELECT HOUR(occurred_at) AS hour, COUNT(*) AS incidents
FROM incidents
GROUP BY hour
ORDER BY incidents DESC
LIMIT 6

   hour  incidents
0    17         44
1    18         27
2    16         23
3     7         23
4     9         23
5     8         17

In [21]:
%%sql
-- Incidents by weekday, Monday first
SELECT DAYNAME(occurred_at) AS weekday, COUNT(*) AS incidents
FROM incidents
GROUP BY DAYNAME(occurred_at), WEEKDAY(occurred_at)
ORDER BY WEEKDAY(occurred_at)

     weekday  incidents
0     Monday         32
1    Tuesday         19
2  Wednesday         26
3   Thursday         18
4     Friday         20
5   Saturday         27
6     Sunday         25

In [22]:
%%sql
-- HAVING: keep only groups that pass a test
SELECT DATE_FORMAT(occurred_at, '%Y-%m') AS month, COUNT(*) AS incidents
FROM incidents
GROUP BY month
HAVING COUNT(*) > 50              -- if you get no rows, lower this number
ORDER BY month

     month  incidents
0  2026-01         54
1  2026-02         65

**Bonus:** `WITH ROLLUP` adds a grand-total row (MySQL syntax). The row with `NULL` in `incident_type` is the total.

In [23]:
%%sql
SELECT incident_type, COUNT(*) AS n
FROM incidents
GROUP BY incident_type WITH ROLLUP

     incident_type    n
0            Crash   42
1           Debris   42
2  Minor collision   41
3  Stalled vehicle   42
4              NaN  167

## 6. JOINs
A join combines rows from two tables using a matching column.
| Join | Keeps |
|---|---|
| `INNER JOIN` | only rows that match in both |
| `LEFT JOIN` | all left rows, matches from the right (NULL if none) |
| `RIGHT JOIN` | all right rows, matches from the left |
| `FULL OUTER JOIN` | not available in MySQL; use `LEFT JOIN ... UNION ... RIGHT JOIN` |
| `CROSS JOIN` | every combination |
| self join | a table joined to itself |

In [24]:
%%sql
-- INNER JOIN: incidents with the road name
SELECT i.incident_id, i.occurred_at, r.road_name, i.incident_type
FROM incidents AS i
INNER JOIN road AS r ON i.road_id = r.road_id
LIMIT 5

   incident_id         occurred_at       road_name    incident_type
0            5 2026-01-04 07:00:00  Briley Parkway  Stalled vehicle
1            7 2026-01-04 16:09:00  Briley Parkway            Crash
2            8 2026-01-05 09:37:00  Briley Parkway  Stalled vehicle
3           13 2026-01-08 17:12:00  Briley Parkway  Stalled vehicle
4           14 2026-01-09 18:17:00  Briley Parkway            Crash

In [25]:
%%sql
-- JOIN + GROUP BY: incidents per road
SELECT r.road_name, COUNT(*) AS incidents, ROUND(AVG(i.injuries), 2) AS avg_injuries
FROM incidents i
JOIN road r ON r.road_id = i.road_id
GROUP BY r.road_name
ORDER BY incidents DESC

           road_name  incidents  avg_injuries
0               I-40         45          0.53
1      Donelson Pike         43          0.67
2  Murfreesboro Pike         42          0.60
3     Briley Parkway         37          0.76

In [26]:
%%sql
-- LEFT JOIN: keep ALL weather days, even days with zero incidents. This matters for your project!
SELECT w.day, w.prcp, COUNT(i.incident_id) AS incidents     -- COUNT(column) ignores NULLs, so unmatched days give 0
FROM weather w
LEFT JOIN incidents i ON DATE(i.occurred_at) = w.day
GROUP BY w.day, w.prcp
ORDER BY incidents ASC, w.day
LIMIT 5

          day  prcp  incidents
0  2026-01-02     0          0
1  2026-01-06     0          0
2  2026-01-10     0          0
3  2026-01-11     0          0
4  2026-01-12     0          0

In [27]:
%%sql
-- Anti-join: days with NO incidents at all
SELECT w.day
FROM weather w
LEFT JOIN incidents i ON DATE(i.occurred_at) = w.day
WHERE i.incident_id IS NULL
LIMIT 5

          day
0  2026-01-02
1  2026-01-06
2  2026-01-10
3  2026-01-11
4  2026-01-12

In [28]:
%%sql
-- RIGHT JOIN: keep every road, even a road with no incidents (add one first)
INSERT INTO road (road_name, speed_limit) VALUES ('Airport Center Dr', 30);
SELECT r.road_name, COUNT(i.incident_id) AS incidents
FROM incidents i
RIGHT JOIN road r ON i.road_id = r.road_id
GROUP BY r.road_name
ORDER BY incidents

OK (1 rows affected)

           road_name  incidents
0  Airport Center Dr          0
1     Briley Parkway         37
2  Murfreesboro Pike         42
3      Donelson Pike         43
4               I-40         45

In [29]:
%%sql
-- FULL OUTER JOIN emulated with UNION (all roads AND all incidents, matched where possible)
SELECT r.road_name, i.incident_id FROM road r LEFT JOIN incidents i ON i.road_id = r.road_id
UNION
SELECT r.road_name, i.incident_id FROM road r RIGHT JOIN incidents i ON i.road_id = r.road_id
ORDER BY road_name, incident_id
LIMIT 5

           road_name  incident_id
0  Airport Center Dr         <NA>
1     Briley Parkway            5
2     Briley Parkway            7
3     Briley Parkway            8
4     Briley Parkway           13

In [30]:
%%sql
-- CROSS JOIN: every road x every incident type (useful to build a complete grid)
SELECT COUNT(*) AS combos
FROM road CROSS JOIN (SELECT DISTINCT incident_type FROM incidents) AS t

   combos
0      20

In [31]:
%%sql
-- SELF JOIN: pair each road with roads that have a higher speed limit
SELECT a.road_name AS slower, b.road_name AS faster
FROM road a JOIN road b ON a.speed_limit < b.speed_limit
ORDER BY a.road_name, b.road_name
LIMIT 6

              slower             faster
0  Airport Center Dr     Briley Parkway
1  Airport Center Dr      Donelson Pike
2  Airport Center Dr               I-40
3  Airport Center Dr  Murfreesboro Pike
4     Briley Parkway               I-40
5      Donelson Pike     Briley Parkway

### The fan-out trap (important for your project)
Joining tables at **different grains** repeats rows and inflates totals. Below, each incident is joined to its month's flight total (one row per incident) and the flights are then summed, so each month's flights are counted once **per incident** instead of once per month.

In [32]:
%%sql
-- WRONG: monthly flights repeated for every incident row
SELECT SUM(a.arrivals + a.departures) AS inflated_total
FROM incidents i JOIN airport_ops a ON DATE_FORMAT(i.occurred_at, '%Y-%m') = a.ops_month;
-- RIGHT: the true total
SELECT SUM(arrivals + departures) AS true_total FROM airport_ops

   inflated_total
0         3989400

   true_total
0       72200

**Fix:** aggregate each table to the same grain (here: month) *before* joining.

In [33]:
%%sql
SELECT a.ops_month,
       a.arrivals + a.departures AS total_ops,
       COALESCE(m.incidents, 0)  AS incidents
FROM airport_ops a
LEFT JOIN (SELECT DATE_FORMAT(occurred_at, '%Y-%m') AS ops_month, COUNT(*) AS incidents
           FROM incidents GROUP BY 1) m ON m.ops_month = a.ops_month
ORDER BY a.ops_month

  ops_month  total_ops  incidents
0   2026-01      23550         54
1   2026-02      22500         65
2   2026-03      26150         48

## 7. Subqueries, CTEs, Views
- **Subquery:** a query inside another query.
- **CTE** (`WITH name AS (...)`): a named, readable step (MySQL 8+).
- **View:** a saved query that behaves like a table.

In [34]:
%%sql
-- Subquery in WHERE: days wetter than average
SELECT day, prcp FROM weather
WHERE prcp > (SELECT AVG(prcp) FROM weather)
ORDER BY prcp DESC, day LIMIT 5

          day  prcp
0  2026-02-06  1.16
1  2026-03-22  1.10
2  2026-02-25  1.03
3  2026-02-21  1.00
4  2026-02-07  0.93

In [35]:
%%sql
-- CTE: build the daily table in readable steps
WITH daily AS (
    SELECT DATE(occurred_at) AS day, COUNT(*) AS incidents
    FROM incidents GROUP BY DATE(occurred_at)
)
SELECT w.day, w.prcp, COALESCE(d.incidents, 0) AS incidents
FROM weather w LEFT JOIN daily d ON d.day = w.day
ORDER BY incidents DESC, w.day LIMIT 5

          day  prcp  incidents
0  2026-01-19  0.28          5
1  2026-01-26  0.68          5
2  2026-02-06  1.16          5
3  2026-02-14  0.28          5
4  2026-03-02  0.12          5

In [36]:
%%sql
-- VIEW: save the integrated daily table once, query it many times
CREATE OR REPLACE VIEW v_daily AS
SELECT w.day,
       w.prcp,
       w.tmax,
       CASE WHEN w.prcp > 0 THEN 'Rain' ELSE 'No rain' END AS weather_state,
       COALESCE(d.incidents, 0) AS incidents,
       a.arrivals + a.departures AS monthly_ops
FROM weather w
LEFT JOIN (SELECT DATE(occurred_at) AS day, COUNT(*) AS incidents
           FROM incidents GROUP BY DATE(occurred_at)) d ON d.day = w.day
LEFT JOIN airport_ops a ON a.ops_month = DATE_FORMAT(w.day, '%Y-%m');
SELECT * FROM v_daily LIMIT 5

OK (0 rows affected)

          day  prcp  tmax weather_state  incidents  monthly_ops
0  2026-01-01  0.00    42       No rain          1        23550
1  2026-01-02  0.00    45       No rain          0        23550
2  2026-01-03  0.00    41       No rain          1        23550
3  2026-01-04  0.37    63          Rain          4        23550
4  2026-01-05  0.00    37       No rain          1        23550

In [37]:
%%sql
-- Use the view: average incidents, rain vs no rain (a core question of the project)
SELECT weather_state, COUNT(*) AS days, ROUND(AVG(incidents), 2) AS avg_incidents, MAX(incidents) AS worst_day
FROM v_daily
GROUP BY weather_state

  weather_state  days  avg_incidents  worst_day
0       No rain    63           1.05          2
1          Rain    27           3.74          5

## 8. Window functions
They calculate across related rows **without collapsing them**. Syntax: `function() OVER (PARTITION BY ... ORDER BY ...)`. (MySQL 8+.)

In [38]:
%%sql
SELECT day, incidents,
       ROW_NUMBER() OVER (ORDER BY incidents DESC, day)                               AS rank_overall,
       SUM(incidents)  OVER (ORDER BY day)                                            AS running_total,
       ROUND(AVG(incidents) OVER (ORDER BY day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS avg_7day
FROM v_daily
ORDER BY day
LIMIT 10

          day  incidents  rank_overall  running_total  avg_7day
0  2026-01-01          1            51              1      1.00
1  2026-01-02          0            71              1      0.50
2  2026-01-03          1            52              2      0.67
3  2026-01-04          4             6              6      1.50
4  2026-01-05          1            53              7      1.40
5  2026-01-06          0            72              7      1.17
6  2026-01-07          2            28              9      1.29
7  2026-01-08          3            16             12      1.57
8  2026-01-09          1            54             13      1.71
9  2026-01-10          0            73             13      1.57

## 9. Set operations
`UNION` (combine, remove duplicates), `UNION ALL` (combine, keep all), `INTERSECT` (in both), `EXCEPT` (in first only). `INTERSECT` and `EXCEPT` need MySQL 8.0.31 or newer; the cell below tells you if your server is older.

In [39]:
try:
    display(sql("""
        SELECT day FROM v_daily WHERE weather_state = 'Rain'
        INTERSECT
        SELECT day FROM v_daily WHERE incidents >= 5
        ORDER BY day LIMIT 5"""))
except pymysql.MySQLError as e:
    print("INTERSECT not supported on this MySQL version:", e.args[1])
    print("Equivalent: use an INNER JOIN or WHERE ... IN (SELECT ...).")

          day
0  2026-01-19
1  2026-01-26
2  2026-02-06
3  2026-02-14
4  2026-03-02

In [40]:
%%sql
-- UNION ALL: stack two result sets with the same columns
SELECT 'wet'  AS kind, COUNT(*) AS days FROM v_daily WHERE prcp > 0
UNION ALL
SELECT 'dry'  AS kind, COUNT(*) AS days FROM v_daily WHERE prcp = 0

  kind  days
0  wet    27
1  dry    63

## 10. Transactions
A transaction groups changes so they succeed or fail **together**. `START TRANSACTION`, then `COMMIT` to keep or `ROLLBACK` to undo. Use this to test risky updates. (Works with InnoDB tables, the MySQL default.)

In [41]:
%%sql
START TRANSACTION;
UPDATE incidents SET injuries = 99;                          -- oops: no WHERE
SELECT MAX(injuries) AS inside_transaction FROM incidents;
ROLLBACK;
SELECT MAX(injuries) AS after_rollback FROM incidents

OK (0 rows affected)
OK (167 rows affected)

   inside_transaction
0                  99

OK (0 rows affected)

   after_rollback
0               2

## 11. Staging and cleaning text data (project skills)
Public CSV files often arrive with dates as text, blanks, trace-precipitation codes like `T`, and duplicate rows. A safe pattern is: **load everything as text into a staging table, then clean into proper types.** Here is the pattern on a tiny **demo** table (not your project data).

In [42]:
%%sql
CREATE TABLE raw_demo (
    rec_id   INT,
    raw_ts   VARCHAR(30),
    raw_prcp VARCHAR(10)
);
INSERT INTO raw_demo VALUES
  (1, '01/05/2026 08:15', '0.00'),
  (2, '01/05/2026 17:40', '0.25'),
  (2, '01/05/2026 17:40', '0.25'),     -- duplicate row
  (3, '01/06/2026 09:05', 'T'),        -- trace of rain
  (4, '01/06/2026 18:30', ''),         -- missing value
  (5, '01/07/2026 07:55', '1.10');
SELECT * FROM raw_demo

OK (0 rows affected)
OK (6 rows affected)

   rec_id            raw_ts raw_prcp
0       1  01/05/2026 08:15     0.00
1       2  01/05/2026 17:40     0.25
2       2  01/05/2026 17:40     0.25
3       3  01/06/2026 09:05        T
4       4  01/06/2026 18:30
5       5  01/07/2026 07:55     1.10

**Step 1: find duplicates.** Group by the columns that should be unique and keep groups that appear more than once.

In [43]:
%%sql
SELECT rec_id, COUNT(*) AS copies FROM raw_demo GROUP BY rec_id HAVING COUNT(*) > 1

   rec_id  copies
0       2       2

**Step 2: remove them safely** by copying `DISTINCT` rows into a new table, checking the count, then swapping names.

In [44]:
%%sql
CREATE TABLE demo_dedup AS SELECT DISTINCT * FROM raw_demo;
SELECT (SELECT COUNT(*) FROM raw_demo) AS rows_before, (SELECT COUNT(*) FROM demo_dedup) AS rows_after

OK (5 rows affected)

   rows_before  rows_after
0            6           5

**Step 3: convert text to real types.** Add a typed column, fill it with `STR_TO_DATE` / `CASE` / `CAST`, and *test with a SELECT first*. Here `T` is treated as 0.005 inch and a blank as NULL (state your rule in your own report).

In [45]:
%%sql
SELECT rec_id, raw_ts,
       STR_TO_DATE(raw_ts, '%m/%d/%Y %H:%i') AS clean_ts,
       CASE WHEN raw_prcp = 'T' THEN 0.005
            WHEN raw_prcp = ''  THEN NULL
            ELSE CAST(raw_prcp AS DECIMAL(5,2)) END AS clean_prcp
FROM demo_dedup
ORDER BY rec_id

   rec_id            raw_ts            clean_ts  clean_prcp
0       1  01/05/2026 08:15 2026-01-05 08:15:00       0.000
1       2  01/05/2026 17:40 2026-01-05 17:40:00       0.250
2       3  01/06/2026 09:05 2026-01-06 09:05:00       0.005
3       4  01/06/2026 18:30 2026-01-06 18:30:00         NaN
4       5  01/07/2026 07:55 2026-01-07 07:55:00       1.100

In [46]:
%%sql
ALTER TABLE demo_dedup ADD COLUMN clean_ts DATETIME, ADD COLUMN clean_prcp DECIMAL(5,3);
UPDATE demo_dedup
SET clean_ts   = STR_TO_DATE(raw_ts, '%m/%d/%Y %H:%i'),
    clean_prcp = CASE WHEN raw_prcp = 'T' THEN 0.005
                      WHEN raw_prcp = ''  THEN NULL
                      ELSE CAST(raw_prcp AS DECIMAL(5,3)) END;
SELECT rec_id, clean_ts, clean_prcp FROM demo_dedup ORDER BY rec_id

OK (0 rows affected)
OK (5 rows affected)

   rec_id            clean_ts  clean_prcp
0       1 2026-01-05 08:15:00       0.000
1       2 2026-01-05 17:40:00       0.250
2       3 2026-01-06 09:05:00       0.005
3       4 2026-01-06 18:30:00         NaN
4       5 2026-01-07 07:55:00       1.100

## 12. MySQL Workbench quick tips and dialect notes
| Task | In MySQL Workbench / MySQL |
|---|---|
| Run the statement under the cursor | Ctrl+Enter (Cmd+Enter on Mac) |
| Run everything in the tab | Ctrl+Shift+Enter |
| Choose the database | `USE sql_lab;` or double-click the schema |
| Import a CSV | right-click the table > *Table Data Import Wizard* |
| Safe-updates error 1175 | filter by primary key, or turn off *Safe Updates* in Preferences |
| Show tables / columns | `SHOW TABLES;` / `DESCRIBE table;` |
| Join text | `CONCAT(a, b)` (not `||`) |
| Replace a view | `CREATE OR REPLACE VIEW` |
| Full outer join | not supported: `LEFT JOIN ... UNION ... RIGHT JOIN` |
| `INTERSECT` / `EXCEPT` | MySQL 8.0.31+ |
| Subquery in `FROM` | alias is **required** |
| Text dates → real dates | `STR_TO_DATE(text, 'format')` |

If you later use another database: SQLite uses `strftime()` instead of `HOUR()`/`DATE_FORMAT()`, and PostgreSQL uses `EXTRACT()`/`TO_CHAR()`.

## 13. Practice (write your own queries)
Each cell is empty. Write the query, run it, and compare with the solutions at the bottom. Start each cell with `%%sql`.

1. List the 10 most recent incidents.
2. Count incidents per road name, highest first.
3. Find the average number of injuries for each incident type; keep types averaging above 0.5.
4. Show the 5 days with the most incidents and whether it rained.
5. Label each incident `rush_hour` = 'Yes' for hours 7-9 and 16-18, otherwise 'No', and count each.
6. For each month, show total flights and incidents per 1,000 flights.
7. Using `v_daily`, compare average incidents on days above vs below the average monthly operations.

In [47]:
%%sql
-- 1

In [48]:
%%sql
-- 2

In [49]:
%%sql
-- 3

In [50]:
%%sql
-- 4

In [51]:
%%sql
-- 5

In [52]:
%%sql
-- 6

In [53]:
%%sql
-- 7

## 14. Mini project path for BNA (no answers, just the route)
Use the same pattern on your real CSVs:
1. Create staging tables with `VARCHAR` columns that match the CSV headers; import with the Workbench wizard.
2. Check: `COUNT(*)`, NULL/blank counts, duplicates via `GROUP BY ... HAVING COUNT(*) > 1`.
3. Convert text dates to real dates (`STR_TO_DATE`), and handle NOAA codes such as `T`.
4. Reduce each table to **one grain** (day) before joining; start the join from the weather days; `COALESCE` the counts.
5. Save as a **view**, then answer questions with `GROUP BY` and `CASE`.
6. Export results to CSV and chart in Excel.

## Solutions (try first!)
Your numbers may differ slightly from any figures you see elsewhere, because the sample data is random (but fixed by a seed).

In [54]:
%%sql
-- 1
SELECT * FROM incidents ORDER BY occurred_at DESC LIMIT 10;
-- 2
SELECT r.road_name, COUNT(*) AS n FROM incidents i JOIN road r USING (road_id) GROUP BY r.road_name ORDER BY n DESC;
-- 3
SELECT incident_type, ROUND(AVG(injuries), 2) AS avg_inj FROM incidents GROUP BY incident_type HAVING AVG(injuries) > 0.5;
-- 4
SELECT day, incidents, weather_state FROM v_daily ORDER BY incidents DESC, day LIMIT 5;
-- 5
SELECT CASE WHEN HOUR(occurred_at) IN (7,8,9,16,17,18) THEN 'Yes' ELSE 'No' END AS rush_hour, COUNT(*) AS n
FROM incidents GROUP BY rush_hour;
-- 6
SELECT a.ops_month, a.arrivals + a.departures AS ops,
       COUNT(i.incident_id) AS incidents,
       ROUND(1000 * COUNT(i.incident_id) / (a.arrivals + a.departures), 2) AS per_1000_ops
FROM airport_ops a
LEFT JOIN incidents i ON DATE_FORMAT(i.occurred_at, '%Y-%m') = a.ops_month
GROUP BY a.ops_month, a.arrivals, a.departures;
-- 7
SELECT CASE WHEN monthly_ops > (SELECT AVG(monthly_ops) FROM v_daily) THEN 'High ops' ELSE 'Lower ops' END AS ops_level,
       COUNT(*) AS days, ROUND(AVG(incidents), 2) AS avg_incidents
FROM v_daily GROUP BY ops_level

,incident_id,occurred_at,road_id,incident_type,injuries,severity
0,167,2026-03-30 16:04:00,4,Stalled vehicle,1,High
1,168,2026-03-30 09:17:00,3,Debris,0,Low
2,166,2026-03-28 17:26:00,2,Minor collision,1,High
3,165,2026-03-28 07:52:00,1,Debris,0,Low
4,163,2026-03-27 17:50:00,2,Stalled vehicle,2,High
5,164,2026-03-27 09:21:00,2,Debris,0,Low
6,162,2026-03-26 04:53:00,1,Minor collision,1,High
7,160,2026-03-24 19:03:00,4,Stalled vehicle,0,Low
8,161,2026-03-24 17:50:00,1,Debris,1,High
9,158,2026-03-24 17:04:00,3,Stalled vehicle,1,High

           road_name   n
0               I-40  45
1      Donelson Pike  43
2  Murfreesboro Pike  42
3     Briley Parkway  37

     incident_type  avg_inj
0  Minor collision     0.54
1           Debris     0.67
2  Stalled vehicle     0.64
3            Crash     0.69

          day  incidents weather_state
0  2026-01-19          5          Rain
1  2026-01-26          5          Rain
2  2026-02-06          5          Rain
3  2026-02-14          5          Rain
4  2026-03-02          5          Rain

  rush_hour    n
0       Yes  157
1        No   10

  ops_month    ops  incidents  per_1000_ops
0   2026-01  23550         54          2.29
1   2026-02  22500         65          2.89
2   2026-03  26150         48          1.84

   ops_level  days  avg_incidents
0  Lower ops    59           2.02
1   High ops    31           1.55